clean_carcassData_NEOR_v2 <- function (data) 
{
  {
    if (is.null(data)) 
      stop("carcass data must be supplied")
  }
  data_clean <- data %>%
                        mutate(
                              ESU_DPS = "Snake River Spring/Summer-run Chinook Salmon ESU", 
                              MPG = "Grande Ronde / Imnaha", 
                              POP_NAME = case_when(River %in% c("Big Sheep Creek", "Lick Creek", "Little Sheep Creek") ~ "Big Sheep Creek", 
                                                   River == "Imnaha River" ~ "Imnaha River mainstem", 
                                                   River %in% c("Bear Creek", "Hurricane Creek", "Lostine River", "Parsnip Creek", "Prairie Creek", "Spring Creek", "Wallowa River") ~ "Lostine River", 
                                                   River == "Minam River" ~ "Minam River", 
                                                   River == "Wenaha River" ~ "Wenaha River"), 
                              TRT_POPID = case_when(River %in% c("Bear Creek", "Hurricane Creek", "Lostine River", "Parsnip Creek", "Prairie Creek", "Spring Creek", "Wallowa River") ~ "GRLOS", 
                                                    River == "Minam River" ~ "GRMIN", 
                                                    River == "Wenaha River" ~ "GRWEN", 
                                                    River %in% c("Big Sheep Creek", "Lick Creek", "Little Sheep Creek") ~ "IRBSH", 
                                                    River == "Imnaha River" ~ "IRMAI"), 
                              Species = "Chinook salmon", 
                              Run = "Spring/summer", 
                              ReportingGroup = case_when(River %in% c("Big Sheep Creek", "Lick Creek", "Little Sheep Creek") ~ "Big Sheep Creek", 
                                                         River == "Imnaha River" ~ "Imnaha River", 
                                                         River == "Lostine River" ~ "Lostine River", 
                                                         River == "Minam River" ~ "Minam River", 
                                                         River %in% c("Bear Creek", "Hurricane Creek", "Parsnip Creek", "Prairie Creek", "Spring Creek", "Wallowa River") ~ "Wallowa River", 
                                                         River == "Wenaha River" ~ "Wenaha River"), 
                              StreamName = River, 
                              TribToName = case_when(River %in% c("Little Sheep Creek", "Lick Creek") ~ "Big Sheep Creek", 
                                                     River %in% c("Wallowa River", "Wenaha River") ~ "Grande Ronde River", 
                                                     River == "Big Sheep Creek" ~ "Imnaha River", 
                                                     River == "Imnaha River" ~ "Snake River", 
                                                     River %in% c("Bear Creek", "Lostine River", "Hurricane Creek", "Minam River", "Prairie Creek", "Parsnip Creek", "Spring Creek") ~ "Wallowa River"), 
                              LocationLabel = Section, 
                              TransectName = SiteID, 
                              SurveyDate = lubridate::ymd(gsub("T00:00:00", "", SurveyDate)),
                              SurveyYear = lubridate::year(SurveyDate),
                              ActivityDate = paste0(SurveyDate, "T00:00:00"), 
                              ActivityId = as.integer(SurveyID), 
                              DatasetId = NA_integer_, 
                              LocationId = NA_integer_, 
                              TargetSpecies = "S_CHN", 
                              Pass = NA_integer_, 
                              StartSurvey = NA_character_, 
                              EndSurvey = NA_character_, 
                              StartTime = Start_Time, 
                              EndTime = End_Time, 
                              Observers = Surveyors, 
                              SurveyMethod = "Ground", 
                              GPSUnit = NA_character_, 
                              Datum = NA_character_, 
                              Weather = NA_character_, 
                              Visibility = Visibility, 
                              SurveyComments = paste0("Survey_Type: ", Survey_Type, "; ", Comments_SurveyEvent), 
                              SampleNumber = GeneticsNumber, 
                              HistoricSampleNumber = NA_character_, CarcassSpecies = "S_CHN", 
                              Sex = case_when(Sex == "M" ~ "Male", Sex == "F" ~ "Female", 
                                              Sex == "J" ~ "Jack", Sex %in% c("Unk", "UNK") ~ "Unknown"), 
                              ForkLength = ForkLength, 
                              PercentSpawned = if_else(Sex == "Male", NA_integer_, as.integer(round(PercentSpawned, 0))), 
                              SpawnedOut = case_when(PercentSpawned < 50 ~ "No", 
                                                     PercentSpawned >= 50 ~ "Yes", 
                                                     TRUE ~ NA_character_), 
                              OpercleLeft = if_else(grepl("LOP", LeftOperclePunchType, ignore.case = TRUE), 
                                                    str_extract(LeftOperclePunchType, "\\d?\\s*LOP"), 
                                                    NA_character_), 
                          #THIS DIDN'T WORK NESTED IF_ELSE() ----
                              # OpercleRight = if_else(
                              #                       grepl("ROP", LeftOperclePunchType, ignore.case = TRUE),
                              #                       str_extract(LeftOperclePunchType, "\\d?\\s*ROP"),
                              #                       if_else( # why isn't this nested if_else working for me?
                              #                         SurveyYear > 2023 & grepl("ROP", RightOperclePunchType, ignore.case = TRUE),
                              #                         str_extract(RightOperclePunchType, "\\d?\\s*ROP"),
                              #                           NA_character_)),
                          #----
                              OpercleRight = if_else(grepl("ROP", LeftOperclePunchType, ignore.case = TRUE),
                                                    str_extract(LeftOperclePunchType, "\\d?\\s*ROP"),
                                                    NA_character_),
                          #THIS IS A HACK SOLUTION FOR 2023 + OPERCLE ----
                              OpercleRight = case_when(SurveyYear >= 2023 ~ RightOperclePunchType,
                                                       TRUE ~ OpercleRight),
                              OpercleRight = case_when(OpercleRight == "ROPunk" ~ NA,
                                                       TRUE ~ OpercleRight),
                          #----
                              PITScanned = case_when(PITscan == "PIT tag present" ~ "Yes", 
                                                     PITscan == "No PIT tag" ~ "No", 
                                                     PITscan == "Not Scanned" ~ "Unknown", 
                                                     ), 
                              PITCode = PIT1, 
                              AdiposeFinClipped = case_when(grepl("ad", FinMark, ignore.case = TRUE) ~ "Yes", 
                                                            grepl("unk", FinMark, ignore.case = TRUE) | FinMark == "" ~ "Unknown", 
                                                            TRUE ~ "No"), 
                              CWTScanned = if_else(`CWT(Y/N)` == "Unk", "Unknown", `CWT(Y/N)`), 
                              SnoutCollected = case_when(grepl("\\d{2}[[:alpha:]]{1}\\d{4}", SnoutID) ~ "Yes", 
                                                         grepl("DB\\d{3}", SnoutID) ~ "Yes", 
                                                         TRUE ~ "No"), 
                              Fins = NA_character_, 
                              Scales = NA_character_, 
                              Otolith = NA_character_, 
                              Count = as.double(Count),
                              
                              # Do i need this? ----
                                  # CarcassComments = Comments, 
                              # ----
                              
                              Latitude = NA_character_, 
                              Longitude = NA_character_, 
                              
                              # Do I need this in the code? ----
                                  # RadioTag = if_else(RadioTag == 1, # If radio tag === 1
                                  #                    "Yes", # then the 'Yes'
                                  #                    "No"), # else 'No'
                              # ----
                            
                              TransmitterType = NA_character_, 
                              Vendor = NA_character_, 
                              SerialNumber = NA_character_, 
                              Frequency = NA_character_, 
                              Channel = NA_character_, 
                              Code = NA_character_, 
                              TagsFloy = NA_character_, 
                              TagsVIE = NA_character_, 
                              TagsJaw = NA_character_, 
                              TagsStaple = NA_character_, 
                              TagsSpaghetti = NA_character_, 
                              MarksVentralFin = NA_character_, 
                              Notes = NA_character_, 
                              QAStatusId = NA_integer_, 
                              CWTCode = CWTcode, 
                              TagsPetersonDisk = NA_character_, 
                              CarcassWPT = as.character(CarcassID), 
                              DNACollected = NA_character_, 
                              ActivityQAStatusId = NA_integer_, 
                              ActivityQAComments = NA_character_, 
                              FieldsheetLink = as.logical(NA), 
                              QAStatusName = NA_character_, 
                              EffDt = NA_character_, 
                              Year = as.integer(Year),
                              AboveWeir = case_when(is.na(AboveOrBelowWeir) | AboveOrBelowWeir == "" ~ NA_character_, 
                                                    AboveOrBelowWeir %in% c("Above Weir", "Diversion", "Lostine Weir") ~ "Yes",
                                                    AboveOrBelowWeir %in% c("Below Weir", "BeforeWeir", "No Weir", "No weir", "Now Weir") ~ "No", 
                                                    TRUE ~ "Unknown"), 
                              AbovePITArray = "Yes", 
                              AboveRST = case_when(River %in% c("Wenaha River", "Wallowa River") ~ "No", 
                                                   TribToName == "Wallowa River" & !River %in% c("Minam River", "Lostine River") ~ "No", 
                                                   River == "Lostine River" & SiteID %in% c("LOS8", "LOS8.1", "LOS8.2", "LOSW", "LOSTULLEY") ~ "No", 
                                                   TRUE ~ "Yes"), 
                              Origin = case_when(Origin %in% c("Nat") ~ "Natural", 
                                                 Origin %in% c("DS.Hat", "Hat") ~ "Hatchery", 
                                                 TRUE ~ "Unknown"), 
                              Mark_Discernible = case_when(OPPunch %in% c("Yes", "No", "yes", "no", "NO") & MarkRecapSizeCategory %in% c("Adult", "Jack", "MiniJ") ~ TRUE, 
                                                           TRUE ~ FALSE), 
                              Recapture = case_when(Mark_Discernible == TRUE & OPPunch %in% c("Yes", "yes") ~ TRUE, 
                                                    TRUE ~ FALSE), 
                              MR_strata = MarkRecapSizeCategory,
                              Length_Age = ifelse(LengthAge > 0,
                                                  LengthAge,
                                                  NA),
                              CWT_Age = ifelse(CWTAge > 0, 
                                               CWTAge, 
                                               NA), 
                              VIE_Age = NA_integer_, 
                              PIT_Age = ifelse(PITage > 0, 
                                               PITage, 
                                               NA), 
                              Fin_Age = ifelse(FinRayAge_Best > 0,
                                               FinRayAge_Best,
                                               NA),
                              Scale_Age = ifelse(BestScaleAge > 0, 
                                                 BestScaleAge, 
                                                 NA),
                              Best_Age = ifelse(BestAge > 0,
                                                BestAge,
                                                NA),
                              Age_Key = ifelse(AgeKey > 0,
                                               AgeKey,
                                               NA)) %>% 

    
    # removed from select ----
        #RadioTag = RadioTag,
    #----
    select(ESU_DPS, MPG, POP_NAME, TRT_POPID, Species, Run, 
           ReportingGroup, StreamName, TribToName, LocationLabel, 
           TransectName, SurveyYear, SurveyDate, ActivityDate, 
           ActivityId, DatasetId, LocationId, TargetSpecies, 
           Pass, StartSurvey, EndSurvey, StartTime, EndTime, 
           Observers, SurveyMethod, GPSUnit, Datum, Weather, 
           Visibility, SurveyComments, SampleNumber, HistoricSampleNumber, 
           CarcassSpecies, Sex, ForkLength, SpawnedOut, PercentSpawned, 
           OpercleLeft, OpercleRight, PITScanned, PITCode, AdiposeFinClipped, 
           CWTScanned, SnoutCollected, Fins, Scales, Otolith, 
           Count, CarcassComments, Latitude, Longitude,  
           TransmitterType, Vendor, SerialNumber, Frequency, 
           Channel, Code, TagsFloy, TagsVIE, TagsJaw, TagsStaple, 
           TagsSpaghetti, MarksVentralFin, Notes, QAStatusId, 
           CWTCode, TagsPetersonDisk, CarcassWPT, DNACollected, 
           ActivityQAStatusId, ActivityQAComments, FieldsheetLink, 
           QAStatusName, EffDt, Year, AboveWeir, AbovePITArray, 
           AboveRST, Origin, Mark_Discernible, Recapture, MR_strata, Length_Age,
           CWT_Age, VIE_Age, PIT_Age, Fin_Age, Scale_Age, Fin_Age, Best_Age, Age_Key)
  return(data_clean)
}
